# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestIos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Material', '~> 2.0'
pod 'Alamofire', '~> 4.7'
pod 'SwiftSpinner', '~> 1.4.1'
  # Pods for TestIos

  target 'TestIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestIosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
